feat(cli): early protection for invalid prometheus prefix
HathorNetwork/hathor-core pull request #1107
Opened 2024-08-07 14:01 UTC by jansegre

### Motivation

We had a report from someone accidentally using an invalid prefix through `HATHOR_PROMETHEUS_PREFIX` which had a message that was hard to understand.

### Acceptance Criteria

- Check for invalid Prometheus prefix when building and give a more helpful message.

### Checklist

- [x] If you are requesting a merge into `master`, confirm this code is production-ready and can be included in future releases as soon as it gets merged

2024-08-09 16:35 UTC, msbrogli approved these changes

2024-08-12 22:27 UTC, glevco requested changes

2024-08-12 22:27 UTC, glevco commented on hathor/builder/resources_builder.py
> +        if self._args.prometheus_prefix and is_prometheus_metric_name_valid(prometheus_prefix):
Missing `not`?

2024-08-12 22:28 UTC, jansegre commented on hathor/builder/resources_builder.py
> +        if self._args.prometheus_prefix and is_prometheus_metric_name_valid(prometheus_prefix):
True! I missed it after refactoring.

2024-08-14 15:48 UTC, jansegre commented on hathor/builder/resources_builder.py
> +        if self._args.prometheus_prefix and is_prometheus_metric_name_valid(prometheus_prefix):
Fixed.

2024-08-14 16:14 UTC, glevco approved these changes

2024-08-14 16:19 UTC, glevco commented on hathor/builder/resources_builder.py
> +        if self._args.prometheus_prefix and is_prometheus_metric_name_valid(prometheus_prefix):
Thanks!

2024-08-14 16:30 UTC, msbrogli approved these changes

2024-08-15 13:06 UTC, merged