feat(p2p): remove sync-v1 code and disable tests
HathorNetwork/hathor-core pull request #1197
Opened 2024-12-23 22:01 UTC by jansegre

### Motivation

We've had sync-v1 in unsafe mode for a while and bridge nodes are on their way out, also all supported releases have sync-v2 on by default, and as far as we know there's no one using sync-v1 anymore.

### Acceptance Criteria

- Remove sync-v1 agent;
- Remove cli flags that enable sync-v1 directly or indirectly;
- Remove enable/disable sync-v1 methods from builder;
- Remove sync-v1 tests;
- Move sync-bridge tests to the normal classes and remove the separate classes;
- No behavior should change apart from not being able to use sync-v1;
- No tests should be removed unless it's specific to sync-v1;

### Checklist

- [x] If you are requesting a merge into `master`, confirm this code is production-ready and can be included in future releases as soon as it gets merged

2025-01-09 16:53 UTC, msbrogli requested changes

2025-01-09 16:57 UTC, jansegre commented on tests/p2p/test_whitelist.py
> -    def test_update_whitelist(self) -> None:
I removed them because they were running only on sync-v1, but I should've changed it to sync-v2, with some refactoring.

2025-01-09 16:57 UTC, jansegre commented on tests/event/test_event_simulation_scenarios.py
True, these changes aren't needed.

2025-01-09 16:59 UTC, jansegre commented on tests/tx/test_tx_serialization.py
> -    def test_serialization_tips(self):
This is a bad diff, the test wasn't removed.

2025-01-16 21:45 UTC, jansegre commented on tests/event/test_event_simulation_scenarios.py
Actually, this change is correct. Because I removed the `__test__ = False` on the `EventReorgTest` class, we don't need a new class, the tests will just run on the `EventReorgTest` class normally.

2025-01-16 22:00 UTC, jansegre commented on tests/p2p/test_whitelist.py
> -    def test_update_whitelist(self) -> None:
Done.

2025-01-17 15:37 UTC, glevco commented on tests/event/test_event_simulation_scenarios.py
I think this is indeed a mistake, I tested it locally and tests in this file are not running. `EventReorgTest` is an unrelated class in another file.

2025-01-17 15:43 UTC, glevco commented on tests/p2p/test_sync.py
> -    def test_block_sync_only_genesis(self) -> None:
Reviving this thread

2025-01-17 15:47 UTC, glevco commented on tests/sysctl/test_p2p.py
>          self.assertEqual(sysctl.get('enabled_sync_versions'), ['v1', 'v2'])
Should we remove this `v1`?

2025-01-17 15:51 UTC, jansegre commented on hathor/builder/cli_builder.py
> -        sync_choice: SyncChoice
Yes.

2025-01-17 15:52 UTC, jansegre commented on tests/sysctl/test_p2p.py
>          self.assertEqual(sysctl.get('enabled_sync_versions'), ['v1', 'v2'])
Yeah, I'll remove it.

2025-01-17 16:27 UTC, jansegre commented on tests/event/test_event_simulation_scenarios.py
I think I was looking at the wrong diff. I now understood what this comment is about, I've reverted all the changes in this file as they are indeed incorrect.

2025-01-17 17:00 UTC, jansegre commented on tests/p2p/test_sync.py
> -    def test_block_sync_only_genesis(self) -> None:
I've restored the tests that were removed but shouldn't have.

2025-01-17 18:15 UTC, jansegre commented on tests/sysctl/test_p2p.py
>          self.assertEqual(sysctl.get('enabled_sync_versions'), ['v1', 'v2'])
Done.

2025-01-23 15:20 UTC, glevco commented on tests/p2p/test_sync.py
> -    def test_block_sync_only_genesis(self) -> None:
Thanks! I'll also let @msbrogli resolve this thread.

2025-01-23 15:21 UTC, glevco commented on hathor/builder/cli_builder.py
> -        sync_choice: SyncChoice
@jansegre this is still missing, right?

2025-01-23 15:22 UTC, glevco commented on tests/simulation/base.py
> -        if enable_sync_v2 is None:
Thanks!

2025-01-23 15:22 UTC, glevco commented on tests/simulation/test_simulator_itself.py
>          enable_sync_v2: bool | None = None
Thanks!

2025-01-23 15:22 UTC, glevco commented on tests/sysctl/test_p2p.py
>          self.assertEqual(sysctl.get('enabled_sync_versions'), ['v1', 'v2'])
Thanks!

2025-01-23 15:24 UTC, glevco approved these changes

2025-01-23 15:29 UTC, jansegre commented on hathor/builder/cli_builder.py
> -        sync_choice: SyncChoice
Oh, right! It's removed now.

2025-01-23 16:44 UTC, msbrogli commented on tests/tx/test_tx_serialization.py
> -    def test_serialization_tips(self):
Ok. Got it. Thanks!

2025-01-23 16:46 UTC, msbrogli commented on tests/event/test_event_simulation_scenarios.py
Thanks!

2025-01-23 20:28 UTC, msbrogli commented on tests/p2p/test_sync.py
> -    def test_block_sync_only_genesis(self) -> None:
Ok. Thanks!

2025-01-23 20:28 UTC, msbrogli approved these changes

2025-01-23 20:38 UTC, merged