fix(api): validate token_uid before using it internally
HathorNetwork/hathor-core pull request #449
Opened 2022-07-27 12:31 UTC by jansegre

2022-07-27 12:41 UTC, pedroferreira1 approved these changes

2022-07-27 15:36 UTC, luislhl approved these changes

2022-07-28 17:37 UTC, msbrogli requested changes
I feel we should fix the memory index and make it raise an exception just like the rocksdb index.

2022-08-01 18:52 UTC, msbrogli approved these changes

2022-08-01 20:49 UTC, merged