tests(feature-activation): implement reorg test
HathorNetwork/hathor-core pull request #660
Opened 2023-06-09 20:08 UTC by glevco

2023-06-16 17:04 UTC, msbrogli requested changes

2023-06-16 17:14 UTC, glevco commented on hathor/simulator/miner/geometric_miner.py
> +        self._signal_bits = signal_bits or []
Indeed that will be the behavior we'll get to, but this CLI mechanism will be described in the Operations milestone of the Feature Activation project, that I haven't started yet. The way it's implemented in this PR is just the base for this next mechanism, so I'm able to test the reorg case now

2023-06-16 17:28 UTC, msbrogli commented on hathor/simulator/miner/geometric_miner.py
> +        self._signal_bits = signal_bits or []
Got it. Are you going to implement this behavior on the geometric miner in the future too? Or should we do it right now?

2023-06-16 17:32 UTC, msbrogli submitted a review, later dismissed

2023-06-16 17:33 UTC, msbrogli commented on hathor/simulator/miner/geometric_miner.py
> +        self._signal_bits = signal_bits or []
As discussed on Slack, it will be done in the future.

2023-06-20 15:39 UTC, jansegre approved these changes

2023-06-20 16:23 UTC, msbrogli approved these changes

2023-06-20 16:24 UTC, merged