chore: move simulator utils functions
HathorNetwork/hathor-core pull request #772
Opened 2023-09-13 13:52 UTC by glevco

### Motivation

What was the motivation for the changes in this PR?

### Acceptance Criteria

- Include here all things that this PR should solve

### Checklist

- [ ] If you are requesting a merge into `master`, confirm this code is production-ready and can be included in future releases as soon as it gets merged

2023-09-19 16:27 UTC, jansegre submitted a review, later dismissed
Looks good to me. Two minor points:

- [ ] This should probably be named a refactor;
- [ ] Should we add a linter check to prevent `from tests* import` or `import tests*`?

2023-09-19 16:49 UTC, msbrogli requested changes

2023-09-19 16:49 UTC, msbrogli commented on hathor/utils/simulator.py
Why not `hathor/simulator/utils.py`?

2023-09-20 20:37 UTC, glevco commented
> - This should probably be named a refactor;
> - Should we add a linter check to prevent `from tests* import` or `import tests*`?

@jansegre both done!

2023-09-20 20:38 UTC, glevco commented on hathor/utils/simulator.py
Moved!

2023-09-20 20:39 UTC, glevco commented on hathor/utils/simulator.py
> +def gen_new_tx(manager, address, value, verify=True):
Done

2023-09-20 20:39 UTC, glevco commented on hathor/utils/simulator.py
> +def add_new_blocks(manager, num_blocks, advance_clock=None, *, parent_block_hash=None,
Done

2023-09-20 20:39 UTC, glevco commented on hathor/utils/simulator.py
> +def add_new_block(manager, advance_clock=None, *, parent_block_hash=None,
Done

2023-09-20 20:39 UTC, glevco commented on hathor/utils/simulator.py
> +def gen_new_double_spending(manager: HathorManager, *, use_same_parents: bool = False,
Done

2023-09-22 16:57 UTC, jansegre submitted a review, later dismissed

2023-09-22 17:25 UTC, msbrogli commented on hathor/utils/simulator.py
Thanks!

2023-09-22 17:25 UTC, msbrogli commented on hathor/utils/simulator.py
> +def gen_new_tx(manager, address, value, verify=True):
Thanks!

2023-09-22 17:25 UTC, msbrogli commented on hathor/utils/simulator.py
> +def add_new_blocks(manager, num_blocks, advance_clock=None, *, parent_block_hash=None,
Thanks!

2023-09-22 17:25 UTC, msbrogli commented on hathor/utils/simulator.py
> +def add_new_block(manager, advance_clock=None, *, parent_block_hash=None,
Thanks!

2023-09-22 17:29 UTC, msbrogli submitted a review, later dismissed

2023-09-27 16:20 UTC, jansegre submitted a review, later dismissed

2023-09-28 15:17 UTC, msbrogli submitted a review, later dismissed

2023-10-10 03:19 UTC, glevco commented
Converted to draft as we wait other PRs to be merged before this one.

2023-11-07 18:39 UTC, msbrogli approved these changes

2023-11-07 21:23 UTC, jansegre approved these changes

2023-11-07 21:28 UTC, merged