fix(p2p): fix update whitelist handler
HathorNetwork/hathor-core pull request #885
Opened 2023-11-30 18:08 UTC by glevco

### Motivation

There are some Twisted errors that are logged raw, causing each log line to become an alert in OpsGenie, as in this incident: https://github.com/HathorNetwork/on-call-incidents/issues/153.

After some investigation, the reason for this is not 100% clear, but there are some suspicions. This PR attempts to fix at least one case that would cause the problem. We've tested a full node running on mainnet for a few days, and by inspecting its logs, it looks like the error has improved.

### Acceptance Criteria

- Remove custom timeout handling in `update_whitelist()` to use `Deferred.addTimeout()`.
- Move the `readBody()` call to be included in the timeout.
- Change `update_whitelist()` so the errback is after the callback, so the errback handles exceptions from the callback.
- Add unit tests for `update_whitelist()`, including cases for success, request error, and request timeout.

### Checklist

- [x] If you are requesting a merge into `master`, confirm this code is production-ready and can be included in future releases as soon as it gets merged

2024-01-12 21:00 UTC, msbrogli requested changes

2024-01-15 19:09 UTC, glevco commented on hathor/p2p/manager.py
> +    def update_whitelist(self, settings: HathorSettings) -> Deferred[None]:
Done in https://github.com/HathorNetwork/hathor-core/pull/885/commits/e777d2b2719949b4a6a6cd9f3c35521d34c8a2a7

2024-01-15 20:04 UTC, msbrogli commented on hathor/p2p/manager.py
> +    def update_whitelist(self, settings: HathorSettings) -> Deferred[None]:
Thanks!

2024-01-15 20:05 UTC, msbrogli submitted a review, later dismissed

2024-01-16 15:33 UTC, jansegre submitted a review, later dismissed

2024-01-17 15:14 UTC, jansegre approved these changes

2024-01-18 23:37 UTC, merged